### ISSUE TITLE
please modernize to haxe 3.x

### ISSUE THREAD

**Issue by jonassmedegaard** [jegoyalu/jarisplayer#10]
Hi,

I have packaged jarisplayer officially for Debian, and succeeded making that work with haxe 3.0 by use of "-D no-pattern-matching" workaround, but with a recent update in Debian to haxe 3.2 that no longer works.

Please consider adjust to new API, as documented at http://old.haxe.org/manual/haxe3/migration

**Comment by jonassmedegaard** [comment]
This bug is tracked in Debian here: https://bugs.debian.org/801250

**Comment by jgmdev** [comment]
Duplicate of #6, I tested and it compiles with latest haxe version.
