### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [jegoyalu/jarisplayer#11]
Hi,

Please consider tagging releases as such in git.  If nothing else, that helps redistributors (like Debian for which I am packaging Jaris FLV Player) more confidently tie tarball/zip files with the more fine-grained development sources as git.

**Comment by jgmdev** [comment]
True, I do it in other project I work https://github.com/wxphp/wxphp/releases but not on this one, while writing I tagged all 2.0 versions, not perfect since versioning is all over the place but at least you can keep now better track https://github.com/jegoyalu/jarisplayer/releases
