### ISSUE TITLE
Problem with C++RTMPD 

### ISSUE THREAD

**Issue by brokenik** [jegoyalu/jarisplayer#4]
Hi! I have tried to use jarisplayer as rtmp client with RTMPD server and after a deep investigation i have discovered that jarisplayer seems to have a issue with RTMP protocol. That's the part of RTMPD error logs : 

<MAP name="" isArray="false">
    <INT32 name="clientSideBuffer">12</INT32>
    <BOOL name="externSeekGenerator">false</BOOL>
    <STR name="fileName">cam9.flv</STR>
    <STR name="fullPath"></STR>
    <BOOL name="keyframeSeek">false</BOOL>
    <STR name="mediaDir">./media/</STR>
    <BOOL name="renameBadFiles">false</BOOL>
    <STR name="requestedStreamName">cam9</STR>
    <MAP name="rtmpMeta" isArray="false">
        <STR name="Server">C++ RTMP Server (http://www.rtmpd.com)</STR>
    </MAP>
    <UINT32 name="seekGranularity">1000</UINT32>
    <STR name="streamType">flv</STR>
</MAP>

As you see - even if i have configured jarisplayer to use stream called cam9 from server - it sends a request for cam9.flv file. Other players such as Flowplayer have no similar issues.

**Comment by jgmdev** [comment]
Added fixes related to rtmp and testing with crtmpserver seems to work. Added some notes to the documentation.txt file: 

https://github.com/jegoyalu/jarisplayer/blob/master/documentation.txt#L60
